name: pre-commit.ci lite
description: pre-commit.ci lite
inputs:
  msg:
    description: commit message to use for autofixing
    required: false
    default: '[pre-commit.ci lite] apply automatic fixes'
  skip_bots:
    description: if true, skip PRs created by bots
    required: false
    default: 'true'
runs:
  using: node20
  main: main.mjs
  post: post.mjs
  post-if: always() && env.PRE_COMMIT_CI_LITE_ARTIFACT == 'true'
